### ISSUE TITLE
Zulu Dependency

### ISSUE THREAD

**Issue by gep13** [JamieMagee/chocolatey#2]
These packages:

https://chocolatey.org/packages/zulu

https://chocolatey.org/packages/zulu11/11.2.3

Appear to do exactly the same thing.  Can I suggest that the zulu package be changed to take a dependency on the zulu11 package?

**Comment by JamieMagee** [comment]
Sure, I want the `zulu` package to always refer to the latest JDK release, but I need to pass an override to the MSI installer to install it to `C:\Program Files\Zulu\zulu` instead of `C:\Program Files\Zulu\zulu-11`. Is there some way that I can do this?

Thanks for the feedback btw, these packages are my first attempt at creating chocolatey packages.

**Comment by gep13** [comment]
@JamieMagee You are very welcome, and thank you for creating the packages in the first place.

The answer to your question really depends on the MSI.  I would assume that it has arguments that you can pass to it to change the installation location, they normally do, but what that is really depends on the installer itself.

Why do you want to change it though?

**Comment by JamieMagee** [comment]
Yeah, the args I pass to the installer are really the only difference between the `zulu` and `zulu11` package. `zulu11` gets installed to `C:\Program Files\Zulu\zulu-11`, and `zulu` gets installed to `C:\Program Files\Zulu\zulu` See [this line](https://github.com/JamieMagee/chocolatey-packages/blob/master/zulu/tools/chocolateyInstall.ps1#L9) for the args.

My intention is for the `zulu` package to be like a `zulu-latest`, so when Azul Systems release Zulu 12 (OpenJDK 12), the `zulu` package will install `zulu12` (to `C:\Program Files\Zulu\zulu`). However, it should still be possible to install `zulu11` (to `C:\Program Files\Zulu\zulu-11`).

Does that make sense?

**Comment by gep13** [comment]
I think so, but I think this can also be achieved through dependencies, unless there is a need for Zulu to be installed to `C:\Program Files\Zulu\zulu`.

For example, right now, if you make the `zulu` package dependent on `zulu11`, a person could walk up to Chocolatey and do `choco install zulu` and they will get zulu11 installed.
Then, when zulu12 comes along, you can change the dependency on the `zulu` package to `zulu12`, and then doing `choco install zulu` would get them `zulu12`.
However, if they wanted a specific version of the zulu, they could choose to do `choco install zulu9`.

So, the only thing that I am not clear on is where you have to install at least one of the zulu installations to `C:\Program Files\Zulu\zulu`.  If this isn't the case, then I would suggest modifying to what I have suggested above.

**Comment by JamieMagee** [comment]
I think there is a reason to install `zulu` to `C:\Program Files\Zulu\zulu`. If I made it a meta-package for `zulu11`, then when `zulu12` is released my `JAVA_HOME` is still pointing to the incorrect folder (`zulu11`), and if I do `choco uninstall` it will leave behind the `zulu11` folder.

**Comment by JamieMagee** [comment]
@gep13 I'm going to close this issue and leave the package as is. If you've got any more suggestions I'll be happy to reopen the discussion.
