### ISSUE TITLE
Zulu8 package outdated

### ISSUE THREAD

**Issue by pascalberger** [JamieMagee/chocolatey#7]
It seems like update of the Zulu8 package is broken. On [Azul page](https://www.azul.com/downloads/zulu-community/?&version=java-8-lts&os=&os=windows&architecture=x86-64-bit&package=jdk) latest version is `8.42.0.23`, with `8.42.0.21` also being available.

**Comment by JamieMagee** [comment]
Closed in 28f17f37c37770e9295069cca70b606a511620e2
